### ISSUE TITLE
README.md typos

### ISSUE THREAD

**Issue by Raboro** [AlexCCavaco/obsidian-exercises#2]
Hi, I found the following typos in the README.md:
- Within it you -> Within it, you (line 5)
- exercises -> exercise (line 5)
- on -> in (line 15)
- Select option -> Select an option (line 19)
- above -> above, (line 25)

I can do a PR with the fix or you can do it by yourself.

**Comment by AlexCCavaco** [comment]
Thank you, I've made the changes and added you to a "Thanks" header.
If you don't want to be there, just message me.
